import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { Inter } from '@next/font/google'
import { 
  Header, 
  Footer, 
  Hero, 
  About, 
  Facts, 
  Skills, 
  Resume, 
  Portfolio, 
  Services, 
  Testimonials,
  Contact
 } from '../components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Youday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="assets/vendor/purecounter/purecounter_vanilla.js"></script>
        <script src="assets/vendor/aos/aos.js"></script>
        <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
        <script src="assets/vendor/typed.js/typed.min.js"></script>
        <script src="assets/vendor/waypoints/noframework.waypoints.js"></script>
        <script src="assets/vendor/php-email-form/validate.js"></script>
        <script src="assets/js/main.js"></script>
      </Head>
      <Header/>
      <Hero/>
      <main id="main">
        <About/>
        <Facts/>
        <Skills/>
        <Resume/>
        <Portfolio/>
        <Services/>
        <Testimonials/>
        <Contact/>
      </main>
      <Footer/>
      <a href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short" /></a>
      {/* <Script src="assets/vendor/purecounter/purecounter_vanilla.js" />
      <Script src="assets/vendor/aos/aos.js" />
      <Script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js" />
      <Script src="assets/vendor/glightbox/js/glightbox.min.js" />
      <Script src="assets/vendor/isotope-layout/isotope.pkgd.min.js" />
      <Script src="assets/vendor/swiper/swiper-bundle.min.js" />
      <Script src="assets/vendor/typed.js/typed.min.js" />
      <Script src="assets/vendor/waypoints/noframework.waypoints.js" />
      <Script src="assets/vendor/php-email-form/validate.js" />
      <Script src="assets/js/main.js" /> */}
    </>
  )
}
