import Head from 'next/head'
import { Inter } from '@next/font/google'
import { 
  Header, 
  Footer, 
 } from '../components'

const inter = Inter({ subsets: ['latin'] })

export default function PortfolioDetails() {
  return (
    <>
      <Head>
        <title>Portfolio Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="assets/vendor/purecounter/purecounter_vanilla.js"></script>
        <script src="assets/vendor/aos/aos.js"></script>
        <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
        <script src="assets/vendor/typed.js/typed.min.js"></script>
        <script src="assets/vendor/waypoints/noframework.waypoints.js"></script>
        <script src="assets/vendor/php-email-form/validate.js"></script>
        <script src="assets/js/main.js"></script>
      </Head>
      <Header/>
      <main id="main">
    <div>
  {/* ======= Breadcrumbs ======= */}
        <section id="breadcrumbs" className="breadcrumbs">
            <div className="container">
            <div className="d-flex justify-content-between align-items-center">
                <h2>Portfoio Details</h2>
                <ol>
                <li><a href="/">Home</a></li>
                <li>Portfoio Details</li>
                </ol>
            </div>
            </div>
        </section>{/* End Breadcrumbs */}
        {/* ======= Portfolio Details Section ======= */}
        <section id="portfolio-details" className="portfolio-details">
            <div className="container">
            <div className="row gy-4">
                <div className="col-lg-8">
                <div className="portfolio-details-slider swiper">
                    <div className="swiper-wrapper align-items-center">
                    <div className="swiper-slide">
                        <img src="assets/img/portfolio/portfolio-details-1.jpg" alt />
                    </div>
                    <div className="swiper-slide">
                        <img src="assets/img/portfolio/portfolio-details-2.jpg" alt />
                    </div>
                    <div className="swiper-slide">
                        <img src="assets/img/portfolio/portfolio-details-3.jpg" alt />
                    </div>
                    </div>
                    <div className="swiper-pagination" />
                </div>
                </div>
                <div className="col-lg-4">
                <div className="portfolio-info">
                    <h3>Project information</h3>
                    <ul>
                    <li><strong>Category</strong>: Web design</li>
                    <li><strong>Client</strong>: ASU Company</li>
                    <li><strong>Project date</strong>: 01 March, 2020</li>
                    <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
                    </ul>
                </div>
                <div className="portfolio-description">
                    <h2>This is an example of portfolio detail</h2>
                    <p>
                    Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.
                    </p>
                </div>
                </div>
            </div>
            </div>
        </section>{/* End Portfolio Details Section */}
</div>

      </main>
      <Footer/>
      <a href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short" /></a>
    </>
  )
}
